feat(lsp): added trim option to make_entry.gen_from_quickfix
nvim-telescope/telescope.nvim pull request #1838
Opened 2022-04-13 12:27 UTC by rowario

Added option to trim results text.
![image](https://user-images.githubusercontent.com/14127958/163179249-fa6f7a92-2870-443d-9f3c-bd9134808da5.png)
![image](https://user-images.githubusercontent.com/14127958/163179316-ddadcdf2-59be-4c90-99ff-be132dedcad6.png)

2022-04-17 12:17 UTC, Conni2461 commented on lua/telescope/make_entry.lua
> +    if opts.trim_text then
We need documentation for this option:.
Docs is autogenerated from this file: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/init.lua

`make_entry.gen_from_quickfix` is used for:
- `lsp_references`
- `lsp_definitions`
- `lsp_type_definitions`
- `lsp_implementations?
- `quickfix`
- `loclist`
- `tagstack`
- `jumplist`

2022-04-17 12:17 UTC, Conni2461 requested changes
If the documentation is here we can do this. Thanks :)

2022-04-18 04:41 UTC, rowario commented
done

2022-04-18 07:22 UTC, Conni2461 commented
Thanks :)

2022-04-18 07:23 UTC, merged