Fix tagrelative option not considered in builtin.tags
nvim-telescope/telescope.nvim pull request #2583
Opened 2023-06-24 09:20 UTC by OscarCreator

# Description

This makes buitin.tags respect tagrelative option. Instead of using `cat` command to show content of tags file `rg` or `grep` is used as they are able to print which file the line in from.

Fixes #1309

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Create a tag which is *not* located in the directory you open nvim but in a subfolder. The tags in the tag file are then relative to the subfolder and not nvim's cwd. Run `Telescope tags` when you have a file open in the subfolder, this should result in showing the tagpaths relative to nvim's cwd.

**Configuration**:
* Neovim version (nvim --version): 0.9.0
* Operating system and version: Ubuntu 22.04.2 LTS

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

2023-06-24 09:25 UTC, OscarCreator commented on lua/telescope/make_entry.lua
> +    if line:sub(1, 1) == "!" then
Should we filter this out when searching instead?

2023-06-24 09:25 UTC, OscarCreator commented on lua/telescope/make_entry.lua
> +      file = tag_path .. "/" .. file
Is a better way to append paths?

2023-06-24 19:06 UTC, jamestrew requested changes
Hey
I'm pretty unfamiliar with ctags so thanks for taking the initiative on this.

Things are looking pretty good, just a couple of thoughts.

2023-06-25 13:12 UTC, OscarCreator commented on lua/telescope/make_entry.lua
> +    if line:sub(1, 1) == "!" then
Done

2023-06-25 13:13 UTC, OscarCreator commented on lua/telescope/make_entry.lua
> +      file = tag_path .. "/" .. file
This should now be fixed.

2023-06-25 19:10 UTC, jamestrew approved these changes

2023-06-25 19:14 UTC, jamestrew commented
thanks!

2023-06-25 19:16 UTC, merged

2023-08-01 00:23 UTC, jamestrew commented
Sorry had to revert this due to some performance issues.

2023-08-01 05:19 UTC, OscarCreator commented
Could you elaborate so I can fix it?

2023-08-01 06:00 UTC, Conni2461 commented
> Sorry had to revert this due to some performance issues.

All good, i'll try to be more active and warn you about code i wouldn't change without "more proper testing". This was my bad, i am sorry

> Could you elaborate so I can fix it?

take a look at https://github.com/nvim-telescope/telescope.nvim/issues/2627

The problem is, for tag files with 100k entries calculating the resulting path for every of these entries from scratch isn't performant. Additionally doing `rg -H -N --no-heading --color never -v '^!|^$'` and parsing it out adds more memory and costs additional cpu time.

Its possible to solve this, but its a none trivial problem to solve.
My idea always was to dynamically generate a function for each file that correctly calculates the path only based on string manipulation because that would be fast enough. But i never gotten around to doing that ...