feat(actions): add delete_mark
nvim-telescope/telescope.nvim pull request #2769
Opened 2023-11-05 21:24 UTC by LittleHendrix

# Description

This PR adds a `delete_mark` action, which can be used in conjunction with the `builtin.marks` picker. 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

**Configuration**:
* Neovim version (nvim --version): `v0.9.4`
* Operating system and version: MacOS Sonoma

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (lua annotations)

2023-11-12 22:48 UTC, jamestrew requested changes
I think you need to run stylua but other than that, it looks good to me

2023-11-26 03:37 UTC, jamestrew approved these changes
lgtm thanks!

2023-11-26 03:37 UTC, jamestrew commented on doc/telescope.txt
oh actually our docs are auto-gen'ed so this was unnecessary.

2023-11-26 03:37 UTC, merged

2023-11-27 14:43 UTC, LittleHendrix commented on doc/telescope.txt
@jamestrew Thank you for the info 👍 I will keep this in mind.