fix(builtin): quickfix entry maker does not used fixed width for file
nvim-telescope/telescope.nvim pull request #2842
Opened 2024-01-03 03:20 UTC by rudiejd

# Description

Fixes https://github.com/nvim-telescope/telescope.nvim/issues/2838 and https://github.com/nvim-telescope/telescope.nvim/issues/2121

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

- [ X ] Locally tested using hidden and non-hidden files
![image](https://github.com/nvim-telescope/telescope.nvim/assets/46619169/5feaa165-a32d-4247-b602-7578eb89ff86)

**Configuration**:
* Neovim version (nvim --version): NVIM v0.10.0-dev-2021+gee2127363 
* Operating system and version: Ubuntu 22.04.3 LTS

# Checklist:

- [ X ] My code follows the style guidelines of this project (stylua)
- [ X  ] I have performed a self-review of my own code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] I have made corresponding changes to the documentation (lua annotations) (N/A)

Apologies if this is a bad solution, I'm still quite new to neovim development

Questions:
- Is it worth renaming the quickfix entry maker? IMO the name

2024-01-03 16:12 UTC, jamestrew requested changes
Looks good so far.

2024-01-03 16:12 UTC, jamestrew commented on lua/telescope/make_entry.lua
> +      display_string = display_string .. " " .. text
```suggestion
      display_string = display_string .. ":" .. text
```

Maybe to stay consistent with other entry makers (vimgrep)

2024-01-03 16:12 UTC, jamestrew commented on lua/telescope/make_entry.lua
>          text = text:gsub("^%s*(.-)%s*$", "%1")
```suggestion
        text = vim.trim(text)
```
Not your change but little refactor

2024-01-03 16:12 UTC, jamestrew commented on lua/telescope/make_entry.lua
> -    { width = vim.F.if_nil(opts.fname_width, 30) },
This means no more `fname_width` option for anything that uses this entry maker right?

Probably should remove that option from the docs (docstring in `builtin/init.lua`).

2024-01-04 02:05 UTC, jamestrew commented
I think there's a couple more missing
https://github.com/nvim-telescope/telescope.nvim/pull/2842/files#diff-1550bb3ef180a28235d51137ee3e2f1f34f115f272ec4b1fad9ea528f0bf9713L431-L439

2024-01-04 02:19 UTC, rudiejd commented
oops right you are, sorry I thought I got those 😅

2024-01-04 02:35 UTC, jamestrew approved these changes
lgtm thanks :+1:

2024-01-04 02:48 UTC, jamestrew commented
@Conni2461 This is a minor breaking change, altering the behavior of `gen_from_quickfix` and removing the `fname_width` option.
Planning to merge this with a `!` in the commit message (undecided on feat vs fix). Also wondering if this calls for an addition to the changelog and new comment in the breaking change issue. Want to run this by you before doing so to confirm.

2024-01-09 08:42 UTC, Conni2461 commented
thanks for your work here :D to both of you. Dont think we need a changelog addition. i think most will be happy with the changes here :laughing:

2024-01-09 09:14 UTC, merged

2024-04-28 01:38 UTC, painhardcore commented
@jamestrew @Conni2461 it's sad that it was not included in v0.1.16. Will it happen in v0.1.17?

2024-05-01 02:36 UTC, jamestrew commented
@painhardcore This change was considering a breaking change so it'll be 0.2.0.