fix: enable_preview true
nvim-telescope/telescope.nvim pull request #3097
Opened 2024-05-12 17:05 UTC by MovieMaker93

# Description

This fix aims to resolve the issue about the "enable_preview" feature that wasn't working. 
Now if you call:
`:Telescope colorscheme enable_preview=true`
while scrolling through the different color scheme options, the live preview is working (change color scheme accordingly)

Fixes #2966

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

I tried two different scenarios:

- :Telescope colorscheme enable_preview=true --> When scrolling through the different color schemes, the theme changes accordingly
- :Telescope colorscheme enable_preview=false -->  When scrolling through the different color schemes, the theme doesn't change

**Configuration**:
* Neovim version (nvim --version): 0.9.4
* Operating system and version: ubuntu 22.04

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (lua annotations)

2024-05-14 01:28 UTC, jamestrew requested changes
I think the existing changes look good.
One thing I forgot to mention about that we should clean up is the existing code to set the previewer.

I _think_ the `if vim.fn.buflisted(bufnr) ~= 1 ...` part of the code path was a prior attempt to enable previews without a previewer, but it either never worked or no longer works. So we can just completely remove this part. It should be redundant now either way. You can also probably remove the `vim.cmd.colorscheme(entry.value)` inside the `define_preview` function in the `new_buffer_previewer` block as well as it's also redundant now.

2024-05-14 17:03 UTC, MovieMaker93 commented
> I think the existing changes look good. One thing I forgot to mention about that we should clean up is the existing code to set the previewer.
> 
> I _think_ the `if vim.fn.buflisted(bufnr) ~= 1 ...` part of the code path was a prior attempt to enable previews without a previewer, but it either never worked or no longer works. So we can just completely remove this part. It should be redundant now either way. You can also probably remove the `vim.cmd.colorscheme(entry.value)` inside the `define_preview` function in the `new_buffer_previewer` block as well as it's also redundant now.

Okay, thanks for the feedback. I've removed both the **vim.fn.buflisted check** and the **cmd.colorscheme** command. In addition, just to be sure, I've tested it again, and it seems to work fine. Let me know if everything is correct on your end.

2024-05-17 03:06 UTC, jamestrew approved these changes

2024-05-17 03:08 UTC, merged

2024-05-17 03:09 UTC, jamestrew commented
Thanks! Looks good and works for me as well.